# NumPy

In [1]:
import numpy as np

In [3]:
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(1000000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 27.9 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 899 ms


### 속도차이가 무려 30배가량 나는 것을확인할 수 있다.

### NumPy의 배열을 다루기전에 임의의 배열을 먼저 만들어보자

In [7]:
data = np.random.randn(2, 3)

In [8]:
data

array([[ 1.61608099, -0.94857177,  0.09623197],
       [-1.49539067,  1.0919459 , -0.62531514]])

###  배열간의 덧셈과 곱셈

In [9]:
data*10

array([[ 16.16080992,  -9.4857177 ,   0.96231966],
       [-14.95390674,  10.91945902,  -6.25315142]])

In [10]:
data+data

array([[ 3.23216198, -1.89714354,  0.19246393],
       [-2.99078135,  2.1838918 , -1.25063028]])

### 데이터 타입

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

### ndarray 생성하기

In [13]:
data1 = [6, 7.5, 8, 0, 1]

In [14]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]

In [16]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### numpy 배열의 속성 검사하기

In [17]:
arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

### 새로운 배열 생성하기

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.empty((2, 3, 2)) # 가비지 값임

array([[[1.00642734e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.72677786e-056]],

       [[3.96488979e-061, 2.87771730e+180],
        [7.97085607e-042, 1.22015233e+165],
        [2.58204865e-057, 8.97195584e-067]]])

In [23]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.full(10,2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [27]:
np.eye(4) #단위 행렬로 채운다

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.identity(4) #마찬가지로 단위 행렬로 채운다

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 캐스팅

In [30]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [31]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [32]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [33]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])