# NumPy

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 29.9 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 999 ms


### 속도차이가 무려 30배가량 나는 것을확인할 수 있다.

### NumPy의 배열을 다루기전에 임의의 배열을 먼저 만들어보자

In [6]:
data = np.random.randn(2, 3)

In [7]:
data

array([[-0.44775244, -0.51062661,  0.34559575],
       [ 0.41540899,  0.27459536,  0.37587702]])

###  배열간의 덧셈과 곱셈

In [8]:
data*10

array([[-4.47752441, -5.10626611,  3.45595746],
       [ 4.15408988,  2.74595357,  3.75877018]])

In [9]:
data+data

array([[-0.89550488, -1.02125322,  0.69119149],
       [ 0.83081798,  0.54919071,  0.75175404]])

### 데이터 타입

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

### ndarray 생성하기

In [12]:
data1 = [6, 7.5, 8, 0, 1]

In [13]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]

In [15]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### numpy 배열의 속성 검사하기

In [16]:
arr2.ndim

2

In [17]:
arr2.shape

(2, 4)

### 새로운 배열 생성하기

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.empty((2, 3, 2)) # 가비지 값임

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.full(10,2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
np.eye(4) #단위 행렬로 채운다

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.identity(4) #마찬가지로 단위 행렬로 채운다

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 캐스팅

In [26]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [27]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [28]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [29]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

### 색인과 슬라이싱

In [30]:
arr = np.arange(10)

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[5]

5

In [33]:
arr[5:8]

array([5, 6, 7])

In [34]:
arr[5:8] = 12

In [35]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [36]:
arr_slice = arr[5:8]

In [37]:
arr_slice

array([12, 12, 12])

In [38]:
arr_slice[1]=12345

In [39]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [40]:
arr_slice[:] = 64

In [41]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [42]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [43]:
arr2d[2]

array([7, 8, 9])

In [44]:
arr2d[0][2]

3

In [45]:
arr2d[0,2]

3

In [46]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr2d[:2, :1]

array([[1],
       [4]])

In [48]:
arr2d[:2, 2]

array([3, 6])

### 불리언 값으로 선택하기

In [49]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [50]:
data = np.random.randn(7,4)

In [51]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [52]:
data

array([[-0.81702392, -0.72202426, -0.71198763,  1.0240083 ],
       [-1.90018873, -0.5108385 , -0.73273218, -1.24590665],
       [-1.01498956,  1.40010906, -0.07339807,  0.4063572 ],
       [ 0.16275159, -1.16369303, -1.63952797,  1.28414986],
       [-0.1494837 ,  0.59146945,  0.6082762 , -0.08101204],
       [ 0.02934716, -0.61820715, -0.02427861, -1.17605004],
       [-1.00936105,  0.02785045,  1.74115401, -0.20638471]])

In [53]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [54]:
data[names == 'Bob']

array([[-0.81702392, -0.72202426, -0.71198763,  1.0240083 ],
       [ 0.16275159, -1.16369303, -1.63952797,  1.28414986]])

In [55]:
data[names == 'Bob', 2:]

array([[-0.71198763,  1.0240083 ],
       [-1.63952797,  1.28414986]])

In [56]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [57]:
data[~(names == 'Bob')]

array([[-1.90018873, -0.5108385 , -0.73273218, -1.24590665],
       [-1.01498956,  1.40010906, -0.07339807,  0.4063572 ],
       [-0.1494837 ,  0.59146945,  0.6082762 , -0.08101204],
       [ 0.02934716, -0.61820715, -0.02427861, -1.17605004],
       [-1.00936105,  0.02785045,  1.74115401, -0.20638471]])

## 팬시 색인

####  팬시 색인은 정수 배열을 사용한 색인을 설명하기 위해 NumPy에서 차용한 단어이다. 

In [58]:
arr = np.empty((8, 4))

In [59]:
for i in range(8):
    arr[i] = i

In [60]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [61]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [62]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [63]:
arr = np.arange(32).reshape((8, 4))

In [64]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [65]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] # 각각 (1, 0), (5, 3), (7, 1), (2, 2)에 대응하는 원소들이 선택된다.

array([ 4, 23, 29, 10])

In [66]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]] # 1행,5행 7행 2행을 0, 3, 1, 2 순서로 인덱싱한다

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

#### 팬시 색인은 슬라이싱과는 달리 선택된 데이터를 새로운 배열로 복사한다는 것을 명심하자.

### 배열 전치와 축 바꾸기

In [67]:
arr = np.arange(15).reshape((3, 5))

In [68]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [69]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [70]:
arr = np.random.randn(6, 3)

In [71]:
arr

array([[-1.23325257,  1.25349664,  2.8238054 ],
       [-1.61740926, -0.27523583,  0.35319182],
       [-0.97805074,  0.70283202,  1.06294223],
       [ 2.9936812 ,  0.49546713, -0.14029091],
       [-0.74898904,  1.42268757,  1.08986835],
       [-0.91263291, -0.92493913,  0.15173316]])

In [72]:
np.dot(arr.T, arr) # 행렬의 내적 구하기 

array([[15.44951843, -0.52629122, -6.4680948 ],
       [-0.52629122,  5.26602144,  5.53017806],
       [-6.4680948 ,  5.53017806, 10.45898509]])

In [73]:
arr = np.arange(16).reshape((2, 2, 4))

In [74]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [75]:
arr.transpose((1, 0, 2)) # 축을 바꾼다고 생각하자 (0, 1, 2)  -> (1, 0, 2)로

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [76]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [77]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

#### transpose와 swapaxes는 데이터를 복사하지 않고 원래 데이터에 대한 뷰를 반환하는 기능이다.

### 유니버셜 함수

In [78]:
arr = np.arange(10)

In [79]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [81]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [82]:
x = np.random.randn(8)

In [83]:
y = np.random.randn(8)

In [84]:
x

array([ 0.08190382, -0.78721091, -0.68393627, -0.62811611, -0.29601648,
        0.08847115,  1.73987716,  0.07565578])

In [85]:
y

array([ 0.04594266, -0.66913543,  1.56350251,  0.76896538, -0.52078481,
        0.95559499, -0.91452414,  0.40418796])

In [86]:
np.maximum(x, y)

array([ 0.08190382, -0.66913543,  1.56350251,  0.76896538, -0.29601648,
        0.95559499,  1.73987716,  0.40418796])

In [87]:
arr = np.random.randn(7) * 5

In [88]:
arr

array([-6.47390339, -0.1854921 , -2.44765003, -0.73044288, -0.41540359,
        3.25500734,  0.15340897])

In [89]:
remainder, whole_part = np.modf(arr)

In [90]:
remainder

array([-0.47390339, -0.1854921 , -0.44765003, -0.73044288, -0.41540359,
        0.25500734,  0.15340897])

In [91]:
whole_part

array([-6., -0., -2., -0., -0.,  3.,  0.])

In [92]:
arr

array([-6.47390339, -0.1854921 , -2.44765003, -0.73044288, -0.41540359,
        3.25500734,  0.15340897])

In [93]:
np.sqrt(arr)

C:\Users\pc\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan,        nan,        nan,        nan,        nan,
       1.80416389, 0.39167457])

In [94]:
np.sqrt(arr, arr)

C:\Users\pc\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan,        nan,        nan,        nan,        nan,
       1.80416389, 0.39167457])

In [95]:
arr

array([       nan,        nan,        nan,        nan,        nan,
       1.80416389, 0.39167457])