# 배열 생성하기

## Ones and zeros

In [1]:
import numpy as np

항목을 초기화하지 않고 2*2 행렬을 만드세요.

이제 X = np.array([1,2,3], [4,5,6], np.int32). 
X의 타입으로 왼쪽과 같이 만드세요

In [2]:
X = np.array([[1,2,3], [4,5,6]], np.int32)


3*3 행렬의 단위행렬을 만드세요

1로 가득찬 3*2의 실수 행렬을 만드세요

이제 x = np.arange(4, dtype=np.int64) 로  1로 가득찬 x의 행렬을 만드세요

In [3]:
x = np.arange(4, dtype=np.int64)


0으로 가득찬 3*2 행렬을 만드세요

x = np.arange(4, dtype=np.int64). x를 사용하여 출력과 같게 만드세요

In [4]:
x = np.arange(4, dtype=np.int64)


6으로 가득찬 새로운 2*5 행렬을 만드세요

x = np.arange(4, dtype=np.int64). X를 이용하여 출력과 같게 만드세요.

In [5]:
x = np.arange(4, dtype=np.int64)


## 존재하는 데이터로부터 정제하기

행렬 [1, 2, 3]을 만드세요.

Let x = [1, 2]. Convert it into an array.

In [6]:
x = [1,2]
np.asarray(x)

array([1, 2])

Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [7]:
X = np.array([[1, 2], [3, 4]])


Let x = [1, 2]. Conver it into an array of `float`.

In [8]:
x = [1, 2]


Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [9]:
x = np.array([30])


Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [10]:
x = np.array([1, 2, 3])


## Numerical ranges

Create an array of 2, 4, 6, 8, ..., 100.

Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

## Building matrices

Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].

In [11]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])


Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

Create an array which looks like below.
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

Create an array which looks like below.
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

Create an array which looks like below. array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])